# Generated by Django 3.0.5 on 2020-06-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='BirthDay',
            field=models.DateField(null=True),
        ),
    ]
