# Generated by Django 3.0.5 on 2020-06-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200607_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
