# Generated by Django 3.0.5 on 2020-06-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_follow'),
        ('users', '0004_profile_name'),
    ]

    operations = [
    ]
