# Generated by Django 3.0.5 on 2020-05-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200518_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorie',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
