# Generated by Django 3.0.5 on 2020-06-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200518_2023'),
        ('blog', '0003_post_categorie'),
    ]

    operations = [
    ]
